name: Build-Dylib
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: clang++ -dynamiclib -arch arm64 modff.cpp -o modff.dylib -stdlib=libc++
      - uses: actions/upload-artifact@v3
        with:
          name: Mod-Hien-Vip
          path: modff.dylib
